import readline from 'node:readline';
import {randomUUID} from 'node:crypto';
import {command} from '../local-bridge/client.mjs';
import {validateRequest} from '../../packages/protocol/index.mjs';

const tools=[{name:'ae_create_ellipse',description:'Create a filled ellipse shape layer.',inputSchema:{type:'object',required:['context','compositionId','name','width','height','position','color'],properties:{context:{type:'string'},compositionId:{type:'integer'},name:{type:'string'},width:{type:'number'},height:{type:'number'},position:{type:'array'},color:{type:'array'}},additionalProperties:false}},{name:'ae_create_rectangle',description:'Create a filled rectangle shape layer.',inputSchema:{type:'object',required:['context','compositionId','name','width','height','position','color'],properties:{context:{type:'string'},compositionId:{type:'integer'},name:{type:'string'},width:{type:'number'},height:{type:'number'},position:{type:'array'},color:{type:'array'}},additionalProperties:false}},{name:'ae_create_solid',description:'Create a solid layer with explicit size and RGB color.',inputSchema:{type:'object',required:['context','compositionId','name','width','height','color'],properties:{context:{type:'string'},compositionId:{type:'integer'},name:{type:'string'},width:{type:'number'},height:{type:'number'},color:{type:'array',items:{type:'number'}}},additionalProperties:false}},{name:'ae_set_bezier_keyframes',description:'Apply Bezier interpolation to all existing keyframes of a supported property.',inputSchema:{type:'object',required:['context','compositionId','layerId','property'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},property:{type:'string',enum:['position','opacity','scale','rotation','anchorPoint']}},additionalProperties:false}},{name:'ae_create_composition',description:'Create and activate a composition.',inputSchema:{type:'object',required:['name','width','height','duration','frameRate'],properties:{name:{type:'string'},width:{type:'number'},height:{type:'number'},duration:{type:'number'},frameRate:{type:'number'}},additionalProperties:false}},
  {name:'ae_get_active_composition',description:'Read the active After Effects composition and issue a short-lived context token.',inputSchema:{type:'object',properties:{},additionalProperties:false}},
  {name:'ae_open_composition',description:'Open a known AE composition by its project item ID and issue a short-lived context token.',inputSchema:{type:'object',required:['compositionId'],properties:{compositionId:{type:'integer'}},additionalProperties:false}},
  {name:'ae_get_layers',description:'Read ordered layer IDs, names, timing, flags, and host match names from the active composition.',inputSchema:{type:'object',required:['context','compositionId'],properties:{context:{type:'string'},compositionId:{type:'integer'}},additionalProperties:false}},
  {name:'ae_get_composition_state',description:'Read composition dimensions, timing, frame rate, current time, and work area.',inputSchema:{type:'object',required:['context','compositionId'],properties:{context:{type:'string'},compositionId:{type:'integer'}},additionalProperties:false}},
  {name:'ae_set_current_frame',description:'Set the active composition playhead to an exact frame for visual inspection.',inputSchema:{type:'object',required:['context','compositionId','frame'],properties:{context:{type:'string'},compositionId:{type:'integer'},frame:{type:'integer',minimum:0}},additionalProperties:false}},
  {name:'ae_get_visible_layers_at_frame',description:'Read visible non-guide layers at an exact composition frame.',inputSchema:{type:'object',required:['context','compositionId','frame'],properties:{context:{type:'string'},compositionId:{type:'integer'},frame:{type:'integer',minimum:0}},additionalProperties:false}},
  {name:'ae_get_composition_markers',description:'Read composition markers for timing recipe verification.',inputSchema:{type:'object',required:['context','compositionId'],properties:{context:{type:'string'},compositionId:{type:'integer'}},additionalProperties:false}},
  {name:'ae_add_composition_marker',description:'Add one labelled composition marker at an exact frame; the change remains visible.',inputSchema:{type:'object',required:['context','compositionId','frame','comment'],properties:{context:{type:'string'},compositionId:{type:'integer'},frame:{type:'integer',minimum:0},comment:{type:'string'}},additionalProperties:false}},
  {name:'ae_import_local_asset',description:'Import one approved local image, video, or Illustrator asset into the AE project panel.',inputSchema:{type:'object',required:['context','compositionId','assetPath'],properties:{context:{type:'string'},compositionId:{type:'integer'},assetPath:{type:'string'}},additionalProperties:false}},
  {name:'ae_add_project_item_layer',description:'Place an imported footage or composition item into the active composition at an explicit position and scale.',inputSchema:{type:'object',required:['context','compositionId','itemId','position','scale'],properties:{context:{type:'string'},compositionId:{type:'integer'},itemId:{type:'integer'},position:{type:'array',items:{type:'number'}},scale:{type:'array',items:{type:'number'}}},additionalProperties:false}},
  {name:'ae_set_track_matte',description:'Set an Alpha or Luma track matte from one existing layer onto another.',inputSchema:{type:'object',required:['context','compositionId','layerId','matteLayerId','type'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},matteLayerId:{type:'integer'},type:{type:'string',enum:['alpha','alphaInverted','luma','lumaInverted']}},additionalProperties:false}},
  {name:'ae_add_rect_mask',description:'Add one rectangular mask to an unlocked layer using explicit layer-space bounds.',inputSchema:{type:'object',required:['context','compositionId','layerId','x','y','width','height'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},x:{type:'number'},y:{type:'number'},width:{type:'number'},height:{type:'number'}},additionalProperties:false}},
  {name:'ae_animate_rect_mask',description:'Animate an existing rectangular mask with exactly two explicit bounds keyframes.',inputSchema:{type:'object',required:['context','compositionId','layerId','maskIndex','keyframes'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},maskIndex:{type:'integer'},keyframes:{type:'array',minItems:2,maxItems:2}},additionalProperties:false}},
  {name:'ae_set_mask_feather',description:'Set one mask’s horizontal and vertical feather in pixels.',inputSchema:{type:'object',required:['context','compositionId','layerId','maskIndex','feather'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},maskIndex:{type:'integer'},feather:{type:'array',items:{type:'number'}}},additionalProperties:false}},
  {name:'ae_add_text_opacity_reveal',description:'Add a fixed per-character text opacity reveal between two times.',inputSchema:{type:'object',required:['context','compositionId','layerId','startTime','endTime'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},startTime:{type:'number'},endTime:{type:'number'}},additionalProperties:false}},
  {name:'ae_set_blend_mode',description:'Set Normal, Multiply, Screen, or Add blend mode on an unlocked layer.',inputSchema:{type:'object',required:['context','compositionId','layerId','mode'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},mode:{type:'string',enum:['normal','multiply','screen','add']}},additionalProperties:false}},
  {name:'ae_add_text_tracking_reveal',description:'Add a fixed per-character tracking reveal between two times.',inputSchema:{type:'object',required:['context','compositionId','layerId','startTime','endTime','tracking'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},startTime:{type:'number'},endTime:{type:'number'},tracking:{type:'number'}},additionalProperties:false}},
  {name:'ae_set_temporal_ease',description:'Set uniform temporal-ease influence on existing Position, Opacity, Scale, or Rotation keyframes.',inputSchema:{type:'object',required:['context','compositionId','layerId','property','influence'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},property:{type:'string',enum:['position','opacity','scale','rotation']},influence:{type:'number'}},additionalProperties:false}},
  {name:'ae_add_text_position_reveal',description:'Add a fixed per-character position reveal between two times.',inputSchema:{type:'object',required:['context','compositionId','layerId','startTime','endTime','offset'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},startTime:{type:'number'},endTime:{type:'number'},offset:{type:'array',items:{type:'number'}}},additionalProperties:false}},
  {name:'ae_animate_mask_feather',description:'Animate one mask’s two-dimensional feather using exactly two keyframes.',inputSchema:{type:'object',required:['context','compositionId','layerId','maskIndex','keyframes'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},maskIndex:{type:'integer'},keyframes:{type:'array',minItems:2,maxItems:2}},additionalProperties:false}},
  {name:'ae_add_gaussian_blur',description:'Add one Gaussian Blur effect with a bounded blur amount.',inputSchema:{type:'object',required:['context','compositionId','layerId','blurriness'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},blurriness:{type:'number',minimum:0,maximum:500}},additionalProperties:false}},
  {name:'ae_create_text_layer',description:'Create an editable text layer in the active composition. The change remains visible.',inputSchema:{type:'object',required:['context','compositionId','text'],properties:{context:{type:'string'},compositionId:{type:'integer'},text:{type:'string'}},additionalProperties:false}},
  {name:'ae_get_position',description:'Read a layer Position value.',inputSchema:{type:'object',required:['context','compositionId','layerId'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'}},additionalProperties:false}},
  {name:'ae_get_transform',description:'Read Anchor Point, Position, Scale, Rotation, Opacity, and 3D status for a layer.',inputSchema:{type:'object',required:['context','compositionId','layerId'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'}},additionalProperties:false}},
  {name:'ae_get_source_info',description:'Read whether a layer is text, footage, or a nested composition and identify its source.',inputSchema:{type:'object',required:['context','compositionId','layerId'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'}},additionalProperties:false}},
  {name:'ae_get_text_document',description:'Read the text content and basic styling of a text layer.',inputSchema:{type:'object',required:['context','compositionId','layerId'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'}},additionalProperties:false}},
  {name:'ae_get_animation_state',description:'Read current transform values and all keyframes for Anchor Point, Position, Scale, Rotation, and Opacity.',inputSchema:{type:'object',required:['context','compositionId','layerId'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'}},additionalProperties:false}},
  {name:'ae_set_position',description:'Set a static layer Position. The change remains visible; no undo is performed.',inputSchema:{type:'object',required:['context','compositionId','layerId','value'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},value:{type:'array',items:{type:'number'}}},additionalProperties:false}},
  {name:'ae_add_position_keyframes',description:'Add exactly two Position keyframes to a layer.',inputSchema:{type:'object',required:['context','compositionId','layerId','keyframes'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},keyframes:{type:'array',minItems:2,maxItems:2}},additionalProperties:false}},
  {name:'ae_add_opacity_keyframes',description:'Add exactly two Opacity keyframes to a layer.',inputSchema:{type:'object',required:['context','compositionId','layerId','keyframes'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},keyframes:{type:'array',minItems:2,maxItems:2}},additionalProperties:false}},
  {name:'ae_add_anchor_point_keyframes',description:'Add exactly two Anchor Point keyframes; changes remain visible.',inputSchema:{type:'object',required:['context','compositionId','layerId','keyframes'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},keyframes:{type:'array',minItems:2,maxItems:2}},additionalProperties:false}},
  {name:'ae_set_layer_timing',description:'Set a layer inPoint and outPoint; the change remains visible.',inputSchema:{type:'object',required:['context','compositionId','layerId','inPoint','outPoint'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},inPoint:{type:'number'},outPoint:{type:'number'}},additionalProperties:false}},
  {name:'ae_add_transform_keyframes',description:'Add exactly two Scale or Rotation keyframes; changes remain visible.',inputSchema:{type:'object',required:['context','compositionId','layerId','property','keyframes'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},property:{type:'string',enum:['scale','rotation']},keyframes:{type:'array',minItems:2,maxItems:2}},additionalProperties:false}},
  {name:'ae_get_keyframes',description:'Read Position or Opacity keyframes from a layer.',inputSchema:{type:'object',required:['context','compositionId','layerId','property'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},property:{type:'string',enum:['position','opacity']}},additionalProperties:false}},
  {name:'ae_set_text_style',description:'Set text size, fill color, and paragraph alignment on a text layer.',inputSchema:{type:'object',required:['context','compositionId','layerId','fontSize','fillColor','justification'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},fontSize:{type:'number'},fillColor:{type:'array',items:{type:'number'}},justification:{type:'string',enum:['left','center','right']}},additionalProperties:false}},
  {name:'ae_set_parent',description:'Parent one unlocked layer to another layer in the active composition.',inputSchema:{type:'object',required:['context','compositionId','layerId','parentLayerId'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},parentLayerId:{type:'integer'}},additionalProperties:false}}
  ,{name:'ae_move_layer_before',description:'Move one unlocked layer directly in front of another layer; the change remains visible.',inputSchema:{type:'object',required:['context','compositionId','layerId','targetLayerId'],properties:{context:{type:'string'},compositionId:{type:'integer'},layerId:{type:'integer'},targetLayerId:{type:'integer'}},additionalProperties:false}}
];
const operationByTool={ae_create_ellipse:['layer.createEllipse'],ae_create_rectangle:['layer.createRectangle'],ae_create_solid:['layer.createSolid'],ae_set_bezier_keyframes:['layer.setBezierKeyframes'],ae_create_composition:['composition.create'],ae_get_active_composition:['composition.getActive',{}],ae_open_composition:['composition.openById'],ae_get_layers:['composition.getLayers'],ae_get_composition_state:['composition.getState'],ae_set_current_frame:['composition.setCurrentFrame'],ae_get_visible_layers_at_frame:['composition.getVisibleLayersAtFrame'],ae_get_composition_markers:['composition.getMarkers'],ae_add_composition_marker:['composition.addMarker'],ae_import_local_asset:['project.importAsset'],ae_add_project_item_layer:['layer.addProjectItem'],ae_set_track_matte:['layer.setTrackMatte'],ae_add_rect_mask:['layer.addRectMask'],ae_animate_rect_mask:['layer.animateRectMask'],ae_create_text_layer:['layer.createText'],ae_get_position:['layer.getPosition'],ae_get_transform:['layer.getTransform'],ae_get_source_info:['layer.getSourceInfo'],ae_get_text_document:['layer.getTextDocument'],ae_set_text_style:['layer.setTextStyle'],ae_set_parent:['layer.setParent'],ae_move_layer_before:['layer.moveBefore'],ae_get_animation_state:['layer.getAnimationState'],ae_set_position:['layer.setPosition'],ae_add_position_keyframes:['layer.addPositionKeyframes'],ae_add_opacity_keyframes:['layer.addOpacityKeyframes'],ae_add_transform_keyframes:['layer.addTransformKeyframes'],ae_add_anchor_point_keyframes:['layer.addAnchorPointKeyframes'],ae_set_layer_timing:['layer.setTiming'],ae_get_keyframes:['layer.getKeyframes']};
operationByTool.ae_animate_rect_mask=['layer.animateRectMask'];
operationByTool.ae_set_mask_feather=['layer.setMaskFeather'];
operationByTool.ae_add_text_opacity_reveal=['text.addOpacityReveal'];
operationByTool.ae_set_blend_mode=['layer.setBlendMode'];
operationByTool.ae_add_text_tracking_reveal=['text.addTrackingReveal'];
operationByTool.ae_set_temporal_ease=['layer.setTemporalEase'];
operationByTool.ae_add_text_position_reveal=['text.addPositionReveal'];
operationByTool.ae_animate_mask_feather=['layer.animateMaskFeather'];
operationByTool.ae_add_gaussian_blur=['layer.addGaussianBlur'];
function result(id,body){return {jsonrpc:'2.0',id,result:body};}
function error(id,code,message){return {jsonrpc:'2.0',id,error:{code,message}};}
async function handle(msg){
  if(msg.jsonrpc!=='2.0' || msg.id===undefined) return null;
  if(msg.method==='initialize') return result(msg.id,{protocolVersion:'2024-11-05',capabilities:{tools:{}},serverInfo:{name:'creative-os-local-mcp',version:'0.1.0'}});
  if(msg.method==='notifications/initialized') return null;
  if(msg.method==='tools/list') return result(msg.id,{tools});
  if(msg.method!=='tools/call') return error(msg.id,-32601,'Method not found');
  const name=msg.params?.name, spec=operationByTool[name];
  if(!spec) return error(msg.id,-32602,'Tool is not allowlisted');
  const args=msg.params?.arguments ?? {};
  try {
    const [operation, fixed]=spec;
    const requestId=randomUUID();
    const request={version:'0.1',requestId,app:'after_effects',operation,arguments:{...fixed,...args}};
    validateRequest(request);
    const response=await command(operation,request.arguments,requestId);
    return result(msg.id,{content:[{type:'text',text:JSON.stringify(response)}],structuredContent:response,isError:!response.success});
  } catch(e) { return error(msg.id,-32602,e.message); }
}
const rl=readline.createInterface({input:process.stdin,crlfDelay:Infinity});
for await(const line of rl) { if(!line.trim()) continue; let msg; try {msg=JSON.parse(line);} catch(e) {process.stdout.write(JSON.stringify(error(null,-32700,'Invalid JSON'))+'\n');continue;} const reply=await handle(msg); if(reply) process.stdout.write(JSON.stringify(reply)+'\n'); }
